### PR TITLE
#156037248 UI/UX revamp

### PR DESCRIPTION
**Pull request by meshnesh**
# What does this PR do?

Revamp the Applications UI/UX

# Description of Task to be completed?

* Switch the application from using a ListView to GridView Layout.
* Implement  SwipeToRefresh.
* Implement ProgressDialog.

## How should this be manually tested?

* Clone the repo.
* Sync/build app.
* Launch app with the device emulator.
* Swipe down on the app to refresh the application and see the dialog.

## What are the relevant pivotal tracker stories?

[#156037248](https://www.pivotaltracker.com/story/show/156037248)

### Screenshots (if appropriate)?

ui-revamp

### CODE REVIEW

**Comment by Jak-Sidious** [comment]
The landscape view of this implementation doesn't look so great. That in itself is a problem mainly because for Android development you are supposed to coni=sider both screen orientations.
When it is optimized for landscape then we can proceed.

**Comment by meshnesh** [comment]
@Jak-Sidious fixed the raised issue.

**Comment by Jak-Sidious** [comment]
Good job with the caches just that the images don't retain the aspect ratio on change of Orientation.
Do fix that then we are good to merge.

**Comment by Jak-Sidious** [comment]
LGTM

**Pull request merged**
